name: Tests
on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Windows, python: '3.9', os: windows-latest, tox: py39}
          - {name: Mac, python: '3.9', os: macos-latest, tox: py39}
          - {name: '3.11', python: '3.11', os: ubuntu-latest, tox: py311-unsafe}
          - {name: '3.10', python: '3.10', os: ubuntu-latest, tox: py310-unsafe}
          - {name: '3.9', python: '3.9', os: ubuntu-latest, tox: py39-unsafe}
          - {name: '3.8', python: '3.8', os: ubuntu-latest, tox: py38-unsafe}
          - {name: '3.7', python: '3.7', os: ubuntu-latest, tox: py37-unsafe}
          - {name: 'PyPy', python: pypy-3.7, os: ubuntu-latest, tox: pypy37-unsafe}
          - {name: '3.11-autoescape', python: '3.11', os: ubuntu-latest, tox: py311-autoescape}
          - {name: '3.10-autoescape', python: '3.10', os: ubuntu-latest, tox: py310-autoescape}
          - {name: '3.9-autoescape', python: '3.9', os: ubuntu-latest, tox: py39-autoescape}
          - {name: '3.8-autoescape', python: '3.8', os: ubuntu-latest, tox: py38-autoescape}
          - {name: '3.7-autoescape', python: '3.7', os: ubuntu-latest, tox: py37-autoescape}
          - {name: 'PyPy-autoescape', python: pypy-3.7, os: ubuntu-latest, tox: pypy37-autoescape}
          - {name: 'Typing', python: '3.9', os: ubuntu-latest, tox: typing}
          - {name: 'Lint', python: '3.9', os: ubuntu-latest, tox: lint}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/setup.cfg"
      - name: cache mypy
        uses: actions/cache@v3
        with:
          path: ./.mypy_cache
          key: mypy|${{ matrix.python }}|${{ hashFiles('setup.cfg') }}
        if: matrix.tox == 'typing'
      - run: pip install tox
      - run: python -m tox -e ${{ matrix.tox }}
